### ISSUE TITLE
Stuck on generating completion

### ISSUE THREAD

**Issue by Stuart-Bush** [strapi/strapi-plugin-open-ai#1]
Open API input correctly.  Logs download the model.  When we try to generate a completion from a prompt, it gets a 200 response from the Open AI server, but nothing shows up in completion. When we tried the same prompt at ChatGPT directly, it immediately responded, so it was not a bandwidth issue.

Here are out log files from the Generate button:

[2023-02-17 17:39:58.743] http: POST /open-ai/settings (38 ms) 200
[2023-02-17 17:40:21.674] http: POST /open-ai/settings (36 ms) 200
[2023-02-17 17:40:36.532] http: POST /open-ai/completions (184 ms) 200

**Comment by pentcle** [comment]
in case anybody else comes here looking for an answer, I ran into the same issue, then updated the Open AI Completion settings to these, and it worked: 

![image](https://user-images.githubusercontent.com/80323528/221232937-8dc53588-6990-4a1d-81d0-c13271a36ba2.png)

**Comment by Mcastres** [comment]
Hello @Stuart-Bush 👋 
What were your settings when you encountered this issue?
