### ISSUE TITLE
[Completion] Does not generate

### ISSUE THREAD

**Issue by Ketcap** [strapi/strapi-plugin-open-ai#4]
When "Generate" has been clicked nothing happens.

I've set OPEN_AI key on my build and re-build the admin panel. 
Instructions followed [from here](https://market.strapi.io/plugins/@strapi-plugin-open-ai)

https://github.com/strapi/strapi-plugin-open-ai/assets/7689820/9f72c907-375a-4c0a-aa58-6bfef9f699b3

**Comment by Mcastres** [comment]
I have fixed the issue and planning on improving the plugin with the upcoming new Strapi version :)
