### ISSUE TITLE
Error on submitting prompt

### ISSUE THREAD

**Issue by squireblackdens** [strapi/strapi-plugin-open-ai#5]
HI there. I have installed and rebuilt as per docs. I have downloaded latest models and selected gpt-3.5-turbo, temp 1, max tokens 1000.

When I try and submit a prompt for completion it hangs and I get the following error thrown in the console:

main.82c8f754.js:913 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at main.82c8f754.js:913:12170
(anonymous) @ main.82c8f754.js:913
Promise.then (async)
be @ main.82c8f754.js:913
onClick @ main.82c8f754.js:913
Pe @ main.82c8f754.js:154
lt @ main.82c8f754.js:1253
ae @ main.82c8f754.js:1253
pe @ main.82c8f754.js:1253
Yo @ main.82c8f754.js:1253
Fs @ main.82c8f754.js:1253
(anonymous) @ main.82c8f754.js:1253
Lt @ main.82c8f754.js:1256
Bn @ main.82c8f754.js:1253
Dl @ main.82c8f754.js:1253
Ur @ main.82c8f754.js:1253
Dr @ main.82c8f754.js:1253

**Comment by Mcastres** [comment]
I have fixed the issue and planning on improving the plugin with the upcoming new Strapi version :)
