### ISSUE TITLE
Completions endpoint is Legacy

### ISSUE THREAD

**Issue by AhmadMuj** [strapi/strapi-plugin-open-ai#6]
Hello
Please update the library to to use v1/chat/completions instead of v1/completions
We are encountering the following error : 
`{
    "error": {
        "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
        "type": "invalid_request_error",
        "param": "model",
        "code": null
    }
}`

**Comment by AhmadMuj** [comment]
I have created the pull request
https://github.com/strapi/strapi-plugin-open-ai/pull/7

**Comment by Mcastres** [comment]
I have fixed the issue and planning on improving the plugin with the upcoming new Strapi version :)
